### ISSUE TITLE
Unclear documentation

### ISSUE THREAD

**Issue by elwinar** [imdario/mergo#10]
I find the description of the `Merge` method quite unclear: after reading, I thought that zero-value fields of the destination were overridden by the matching field of the source. I had to dig in the source code and the tests to understand it worked the other way around.

It may have to do with me being tired, but I think that providing a simple and visual example that can be copy-pasted for demonstration would be a nice thing to have in the readme. For example:

```go
package main

import (
	"fmt"
	"github.com/imdario/mergo"
)

type Foo struct {
	A string
	B int64
}

func main() {
	src := Foo{
		A: "one",
	}

	dest := Foo{
		A: "two",
		B: 2,
	}

	mergo.Merge(&dest, src)

	fmt.Println(dest)
	// Will print
	// {one 2}
}
```

**Comment by imdario** [comment]
Done. Thanks for you feedback!
