### ISSUE TITLE
Bug: Map fails when struct has an interface member

### ISSUE THREAD

**Issue by alexkursell** [imdario/mergo#100]
```mergo``` panics when the following code is run:

```go
type S struct {
	Member interface{}
}

func main(){
	m := make(map[string]interface{})
	m["Member"] = "anything"

	st := &S{}
	mergo.Map(st, m)

	fmt.Printf("%+v", st)
}
```

producing ```panic: reflect: call of reflect.Value.IsNil on string Value```. This panic occurs if any interface type at all is specified for ```Member```

**Comment by kidlj** [comment]
Any update on this?

**Comment by imdario** [comment]
@kidlj Fixed in master.
