### ISSUE TITLE
Add benchmarks

### ISSUE THREAD

**Issue by vdemeester** [imdario/mergo#109]
to make we keep improving performance… or at least we don't degrade it :angel:

**Comment by imdario** [comment]
Shall we try to benchmark real-world scenarios? I think we could work with Docker examples.

PS: I'm back, for real :wave:

**Comment by vdemeester** [comment]
@imdario yeah we can :) I think there is docker example (in `docker/cli` and `docker/app` for compose file merging) and might be also some k8s examples

**Comment by imdario** [comment]
Actually, I was thinking on giving mergo `go generate` powers. These benchmarks are going to be useful to test and compare this code generation approach.
