### ISSUE TITLE
WithOverride should be able to check types

### ISSUE THREAD

**Issue by silvin-lubecki** [imdario/mergo#111]
Merging slices with the `WithOverride` option does not check that the slices have the same type. But before #96, one could use the `WithAppendSlice` option to have a "strict" override, failing if the types are different (check this test, failing now with mergo master https://github.com/docker/app/blob/master/types/parameters/merge_test.go#L10 ).

I propose to add an option, like `WithStrictOverride` to get this "feature" back, which will fail in this case.

**Comment by thaJeztah** [comment]
@vdemeester @silvin-lubecki looks like this can be closed (fixed by https://github.com/imdario/mergo/pull/112)

**Comment by vdemeester** [comment]
Indeed, thanks :+1:
