### ISSUE TITLE
Issue #84 not fully solved yet

### ISSUE THREAD

**Issue by yannh** [imdario/mergo#115]
Hello :wave:  I wrote the following test which fails (renamed from a Issue84 test with a similar problem)
```
func TestIssue84MergeMapWithNilValueToStructWithOverride(t *testing.T) {
	p1 := map[string]interface{}{
		"A": 0, "B": 1, "C": 2,
	}
	p2 := map[string]interface{}{
		"D": nil,
	}
	if err := Map(&p1, p2, WithOverride); err != nil {
		t.Fatalf("Error during the merge: %v", err)
	}
	if _, ok := p1["D"]; !ok  {
		t.Errorf("p1 should contain D: %+v", p1)
	}
}
```

It prints: 
```
p1 should contain D: map[A:0 B:1 C:2]
```
Would I be correct to expect p1 to contain map[A:0 B:1 C:2 D:nil] ?
If yes, I can have a go at fixing it - let me know if you want to reopen #84 (it seems to be a similar problem) or if I should create a new test file. Thanks!

**Comment by imdario** [comment]
PR for this issue merged
