### ISSUE TITLE
how to merge slice struct

### ISSUE THREAD

**Issue by ystyle** [imdario/mergo#121]
```
package main

import (
	"fmt"
	"github.com/imdario/mergo"
)

type Order struct {
	A       string
	B       int64
	Details []Detail
}

type Detail struct {
	A string
	B string
}

func main() {
	src := Order{
		A: "one",
		B: 2,
		Details: []Detail{
			{
				B: "B",
			},
		},
	}
	dest := Order{
		A: "two",
		Details: []Detail{
			{
				A: "one",
			},
		},
	}
	mergo.Merge(&dest, src)
	fmt.Printf("%+v",dest)
	// Will print
	// {A:two B:2 Details:[{A:one B:}]}
	// how to get result
	// {A:two B:2 Details:[{A:one B:B}]}
}
```
Will print
```
{A:two B:2 Details:[{A:one B:}]}
```
I want to got 
```
{A:two B:2 Details:[{A:one B:B}]}
```

I want to merge two sorted Detail slice data

**Comment by BiteBit** [comment]
This may be what you want.
https://godoc.org/github.com/imdario/mergo#WithAppendSlice

**Comment by ystyle** [comment]
@BiteBit 
```
    err := mergo.Merge(&dest, src, mergo.WithAppendSlice)
    if err != nil {
        panic(err)
    }
    fmt.Printf("%+v", dest)
    // {A:two B:2 Details:[{A:one B:} {A: B:B}]}
```


```
    err := mergo.Merge(&dest, src, mergo.WithOverride, mergo.WithAppendSlice)
    if err != nil {
        panic(err)
    }
    fmt.Printf("%+v", dest)
    // {A:one B:2 Details:[{A:one B:} {A: B:B}]}
```


both not `{A:two B:2 Details:[{A:one B:B}]}`

**Comment by PeerXu** [comment]
I have the same problem.

```

**Comment by PeerXu** [comment]
I have the same problem.

```
package main

import (
	"fmt"

	"github.com/imdario/mergo"
)

func main() {
	dst := map[string]interface{}{
		"inter": map[string]interface{}{
			"a": "1",
			"b": "2",
		},
	}

	src := map[string]interface{}{
		"inter": map[string]interface{}{
			"a": "3",
			"c": "4",
		},
	}

	fmt.Println(src) // map[inter:map[a:3 c:4]]
	fmt.Println(dst) // map[inter:map[a:1 b:2]]
	mergo.Merge(&dst, src)
	fmt.Println(src) // map[inter:map[a:3 c:4]]
	fmt.Println(dst) // map[inter:map[a:1 b:2 c:4]], but expect map[inter:map[a:3 b:2 c:4]]
}
```

**Comment by imdario** [comment]
Solved and merged, although through a different PR (#151)

**Comment by scorpinxia** [comment]
seem  this is not fixed
`package main

import (
	"fmt"
	"github.com/imdario/mergo"
)

type Order struct {
	A       string
	B       int64
	Details []Detail
}

type Detail struct {
	A string
	B string
}

func main() {
	src := Order{
		A: "one",
		B: 2,
		Details: []Detail{
			{
				B: "B",
			},
		},
	}
	dest := Order{
		A: "two",
		Details: []Detail{
			{
				A: "one",
			},
		},
	}
	mergo.Merge(&dest, src)
	fmt.Printf("%+v",dest)
	// Will print
	// {A:two B:2 Details:[{A:one B:}]}
	// how to get result
	// {A:two B:2 Details:[{A:one B:B}]}
}
`
Will print
`
{A:two B:2 Details:[{A:one B:}]}
`
I want to got
`
{A:two B:2 Details:[{A:one B:B}]}
`

**Comment by imdario** [comment]
@scorpinxia Check imdario/mergo#126

**Comment by scorpinxia** [comment]
> 

I try it, but it failed.   i just update above comment

**Comment by scorpinxia** [comment]
@imdario  I try this example [](https://github.com/imdario/mergo/pull/126) the result is same with mergo.Merge(&dest, src
```
package main

import (
	"fmt"
	"github.com/imdario/mergo"
)

type Order struct {
	A       string
	B       int64
	Details []Detail
}

type Detail struct {
	A string
	B string
}

func main() {
	src := Order{
		A: "one",
		B: 2,
		Details: []Detail{
			{
				B: "B",
			},
		},
	}
	dest := Order{
		A: "two",
		Details: []Detail{
			{
				A: "one",
			},
		},
	}
	mergo.Merge(&dest, src, mergo.WithSliceDeepCopy)
	fmt.Printf("%+v",dest)
	// Will print
	// {A:two B:2 Details:[{A:one B:}]}
	// how to get result
	// {A:two B:2 Details:[{A:one B:B}]}
}

**Comment by imdario** [comment]
@scorpinxia I'll check this later.

**Comment by aengelberg** [comment]
Just bumping this ticket - I'm also noticing issues deep-merging structs within slices, seeing similarly buggy behavior as above.

I noticed when stepping through it locally that in the `deepMerge` function, `dst.CanSet()` becomes false when it's one of the elements in a slice. So even when `WithSliceDeepCopy` is enabled, the inner values can't actually be deep-copied. Would love for a second pair of eyes to confirm, though.
