### ISSUE TITLE
Feature :  Override Nil on merge 

### ISSUE THREAD

**Issue by VimalKumarS** [imdario/mergo#123]
Request feature : override nil, if want to nullify dest with nil value

        dest:= make(map[string]interface{})
	src :=make(map[string]interface{})

	dest["col1"]=2
	dest["col2"]=3
	dest["col3"]=3
	src["col1"]=nil
	src["col2"]=4
	src["col2"]=nil

	mergo.Merge(&dest, src,mergo.WithOverride)

I tried to change code in order to set nil  line#96

```
if srcElement.IsNil() {
			if (config.overwrite) {
				dst.SetMapIndex(key, srcElement)
				}
				continue
				}
```

thanks
Vimal

**Comment by github4jiawen** [comment]
[#89](https://github.com/imdario/mergo/issues/89#issuecomment-562954181) may help

**Comment by rusdevops** [comment]
I hope [128 PR](https://github.com/imdario/mergo/pull/128) resolve this issue.

**Comment by imdario** [comment]
This is fixed in master, it will be available in next release 0.3.10.

**Comment by rusdevops** [comment]
@imdario, thanks, we will be very grateful for the early release of the new release - **0.3.10**.

**Comment by loeffel-io** [comment]
Need this too

**Comment by imdario** [comment]
@rusdevops Sorry, I wasn't able to do an early release. I'm working fixing 0.3.9 specific bugs and merging other PRs.

**Comment by imdario** [comment]
Reopening this issue as PR #105 introduced too many bugs, and this issue isn't fixed with the current state of master.
