### ISSUE TITLE
"Nice example" from readme no longer gives a valid result

### ISSUE THREAD

**Issue by rexposadas** [imdario/mergo#13]
I was using mergo prior to April 6th, 2015. So I did `go get -u github.com/imdario/mergo` and ran the "Nice example" in the readme. The result was:

`{two 2}`  and not as advertised:

    fmt.Println(dest)
    // Will print
    // {one 2}

**Comment by imdario** [comment]
The example is fixed. Destination's non-zero fields are not overrided by design. Otherwise it would be just a instance cloner.
