### ISSUE TITLE
Support for deep merge with copy by value?

### ISSUE THREAD

**Issue by frickenate** [imdario/mergo#134]
Am I correct to assume there is no support for a deep merge that always makes cloned copies of all nested members? Right now running `Merge()` with a source and destination containing nested elements—for example—a `map[string]map[string]struct{}`, makes a copy of the the outer `map[string]`, but each inner `map[string]struct{}` in destination winds up simply pointing to the same maps in memory that exist in source. The result being that modifying any nested map in destination after the merge also affects the source.

Really looking for the ability to force a deep clone of everything, where all pointers, maps, and slices are copied/cloned/duplicated from source to destination by value, rather than reusing the existing object.

**Comment by georgysavva** [comment]
Hey. Any update on this?

**Comment by imdario** [comment]
@frickenate There is no support currently. There won't be in the current implementation of Mergo, but I'm thinking of doing a major rewrite of the library. This could be a configurable behavior.

In the meantime, I think this can be achieved using transformers: https://github.com/imdario/mergo#transformers

**Comment by georgysavva** [comment]
Understood. Thanks!
