### ISSUE TITLE
Is there any nice way to merge different types?

### ISSUE THREAD

**Issue by doortts** [imdario/mergo#136]
Thank you for the great work.

I read mergo supports only the same struct type. 
But I wonder there is any nice way to merge different types.

For example, something like following style.

```
type A struct {
	Name string
	Age  uint8
}

type B struct {
	A
	Address string
}

func TestMergo(t *testing.T) {
	a := &A{
		"Suwon", 16,
	}

	b := &B{}

	err := mergo.Merge(b, *a)

	if b.Name != "Suwon" {
		t.Fatalf("%v %v", b.Name, err)
	}
}

```

**Comment by imdario** [comment]
This was a decision I took seven years ago. Maybe I can check it again. Anyway, I need some time to attend all the pending PRs and issues.

**Comment by thinkgos** [comment]
I use [http://github.com/jinzhu/copier](copier)  to  copy value from struct to different struct and more

**Comment by imdario** [comment]
@doortts I adapted your example as a real test in Mergo. This would be the idiomatic way to do it, but I'm not sure what can happen if your type isn't local to your package.

```go
type embeddedTestA struct {
	Name string
	Age  uint8
}

type embeddedTestB struct {
	embeddedTestA
	Address string
}

func TestMergeEmbedded(t *testing.T) {
	a := &embeddedTestA{
		"Suwon", 16,
	}

	b := &embeddedTestB{}

	err := Merge(&b.embeddedTestA, *a)

	if b.Name != "Suwon" {
		t.Fatalf("%v %v", b.Name, err)
	}
}
```
