### ISSUE TITLE
0.3.9 no longer possible to override map fields with a different type

### ISSUE THREAD

**Issue by AlbertoBarba** [imdario/mergo#143]
https://play.golang.org/p/JPC8iO5ehZK

The provided code works as expected with version 0.3.8, but returns error in 0.3.9

**Comment by Charles546** [comment]
Having the same issue with my app also.

**Comment by imdario** [comment]
Ok, I'm going fix this during this week.

**Comment by AlbertoBarba** [comment]
Hey @imdario, is there any news about this?

**Comment by imdario** [comment]
@AlbertoBarba Sorry, I had very little free time. I'll try to check issues during this week.

**Comment by imdario** [comment]
Resolved by reverting PR #105
