### ISSUE TITLE
Question: Why dst UnsafeAddr need multiply 17 as visit map key ?

### ISSUE THREAD

**Issue by kaka19ace** [imdario/mergo#145]
Source Code: https://github.com/imdario/mergo/blob/v0.3.9/merge.go#L69 
```golang
	....
	if dst.CanAddr() {
		addr := dst.UnsafeAddr()
		h := 17 * addr
		typ := dst.Type()
		seen := visited[h]
		...
	}
	...
```

**Comment by imdario** [comment]
The basis of mergo is src/reflect/deepequal.go. At some point, the Go team implemented the hashing of pointers with this code. I checked the current implementation and it has changed a lot.

This confirms the need to do a clean room implementation, as it is getting cumbersome to maintain the library.
