### ISSUE TITLE
reflect.Value has no field or method IsZero

### ISSUE THREAD

**Issue by iancboswell** [imdario/mergo#154]
I'm getting this error after updating to the most recent version of mergo:

```
imdario/mergo/merge.go:268:25: newSlice.Index(i).IsZero undefined (type reflect.Value has no field or method IsZero)
```

My Go version is 1.12.15. I'm wondering if IsZero was added into a more recent version of Go? Any chance this part of the codebase can be backwards-compatible somehow? Or is something else at play here? Checking out `4d20b46` gets rid of the problem for me.

**Comment by imdario** [comment]
@iancboswell It appears in Go 1.13: https://github.com/golang/go/issues/7501

A simple way to keep backward compatibility would be copying the function reflect.IsZero as it was implemented in 1.13: https://go-review.googlesource.com/c/go/+/171337/9/src/reflect/value.go

**Comment by imdario** [comment]
Closing the issue as the code using IsZero is gone after reverting PR #105. I'll take into account for future PRs to keep backward compatibility.

In any case, keep in mind that the official support policy of Go is to keep the last two major releases. Go 1.13 is not longer supported by the Go team.

**Comment by iancboswell** [comment]
Thanks! Noted re: Go major versions, though I actually have to run on an even older version of Go (1.12) when I deploy to Google App Engine. They do have an issue with not keeping up to date generally, but I don't think that kind of production scenario is uncommon.
