### ISSUE TITLE
Date columns getting overriden when merging

### ISSUE THREAD

**Issue by vitroz** [imdario/mergo#157]
Hi guys, I am facing a small issue with Time columns.

```
	if err := mergo.Merge(dest, src, mergo.WithOverride); err != nil {
		return err
	}
```

Using `mergo.WithOverride`, when I try to merge my DB record with an incoming API patch request, and this request only has an updated text field, like Name, for example, all date columns are set to `0001-01-01 00:00:00`. If I provide the date columns, everything works as expected. But I am now obliged to always provide all the date field columns when I am updating a record, to prevent the date fields from getting set to `0001-01-01 00:00:00`.

I tried the docs approach, using a `TimeTransformer` 

````
	if err := mergo.Merge(dest, src, mergo.WithTransformers(timeTransformer{})); err != nil {
		return err
	}
````

And it fixed the problem of the date columns getting set to `0001-01-01 00:00:00` when they are not supplied, however, when I supply them, they dont get merged, the existing value stays the same on the destination.

Has anyone faced this kind of issue?

Is there a way where I can user, mergo.withOverride alongside a Transformer?

Thanks

**Comment by vitroz** [comment]
Closing issue. Found answer on #52

**Comment by imdario** [comment]
@vitroz Nice. Thank you!
