### ISSUE TITLE
inefficient and unused default merge conditional

### ISSUE THREAD

**Issue by bionoren** [imdario/mergo#160]
As of this writing, merge.go:274-278 read thus:
```
v := fmt.Sprintf("%v", src)
if v == "TestIssue106" {
	fmt.Println(mustSet)
	fmt.Println(dst.CanSet())
}
```

This is the only place the text "TestIssue106" occurs in this codebase (confirmed via `find . -type f | xargs grep "TestIssue106"`). I suspect this is leftover from a recent testing refactor. The conditional isn't so bad, but the Sprintf overhead adds up for large structs. In addition to the possibility for unexpected prints if someone's struct happens to contain that string...

This code is unused and should be removed.

**Comment by imdario** [comment]
New version released: https://github.com/imdario/mergo/releases/tag/v0.3.11 Thanks!
