### ISSUE TITLE
Merge with override using bool values gives unexpected behavior.

### ISSUE THREAD

**Issue by neppi** [imdario/mergo#165]
```go
type SomeBools struct {
	BoolA bool
	BoolB bool
	BoolC bool
	BoolD bool
}

func testBoolMerge() {
	A := SomeBools{
		BoolA: true,
		BoolB: true,
		BoolC: false,
		BoolD: false,
	}
	B := SomeBools{
		BoolA: true,
		BoolB: false,
		BoolC: true,
		BoolD: false,
	}

	log.Info("merging with Override option")
	log.Info(A)
	log.Info(B)
	mergo.Merge(&A, B, mergo.WithOverride)
	log.Info(A)
}


```
results in 

``` text
  INFO ▶ testBoolMerge ▶  merging with Override option
  INFO ▶ testBoolMerge ▶  {true true false false}
  INFO ▶ testBoolMerge ▶  {true false true false}
  INFO ▶ testBoolMerge ▶  {true true true false}
```
BoolB is expected to be false too.

**Comment by dgurns** [comment]
Having the same issue here. Merging will update `false` to `true`, but will not update `true` to `false`, since perhaps it sees the incoming `false` as a zero value. Seems like a pretty basic use case though. Am I missing something?

**Comment by dionysius** [comment]
Yes, this is definitely it what @dgurns wrote. `false` is the zero value for `bool` so it is IMO correct that mergo acts that way. You have the option `WithOverwriteWithEmptyValue` to include zero values also to ovewrite

**Comment by imdario** [comment]
@dgurns Please refer to the official documentation about zero values: https://golang.org/ref/spec#The_zero_value

As you already wrote, and @dionysius confirmed, `false` is the zero value for bool.

**Comment by clarkmcc** [comment]
@imdario The behavior is the same for pointers to boolean values, is that expected? Is there a way to get around this behavior using a custom transformer? Here is a reproducable script.

```go
// Case #1 - Expected output to be true, actual output is true
tr := true
fa := false
a := obj{A: &fa}
b := obj{A: &tr}
err := mergo.Merge(&a, b, mergo.WithOverride)
if err != nil {
    panic(err)
}
fmt.Println(*a.A)

// Case #1 - Expected output to be false, actual output is true
tr = true
fa = false
a = obj{A: &tr}
b = obj{A: &fa}
err = mergo.Merge(&a, b, mergo.WithOverride)
if err != nil {
    panic(err)
}
fmt.Println(*a.A)
```
