### ISSUE TITLE
field name by struct tag

### ISSUE THREAD

**Issue by vtolstov** [imdario/mergo#172]
What you think about adding ability to specify src name via struct tag?
For example i have dst like
```go
struct Config {
  Name string `sometag:"fio"`
}
```

and have src like
```go
map[string]interface{}{"fio": "XX XX XX"}
```

**Comment by vtolstov** [comment]
gentle ping..
As i saw the code changes are not big and can be enabled by option for example

**Comment by imdario** [comment]
@vtolstov Unfortunately, I'm not able to deliver this kind of feature. Also, the current version is frozen for new features. I'll work in a new codebase from scratch at some point, so I'm taking note of this.
