### ISSUE TITLE
[Proposal]skipping fields

### ISSUE THREAD

**Issue by leopku** [imdario/mergo#173]
* Skip permanently by tag mergo:"..."

For example, ID and UserID would never merged every time
```go
type Comment struct {
	ID           int32       `db:"id" json:"id" mergo:"skip"`
	Type         int32       `db:"type" json:"type"`
	Content      null.String `db:"content" json:"content,omitempty"`
	AdminContent null.String `db:"admin_content" json:"adminContent,omitempty"`
	UserID       int32       `db:"user_id" json:"userId" mergo:"skip"`
}
```

* Skip temporally by something like WithSkipOption

For example, AdminContent would not merged only this time.

```go
skipFields := []string{"AdminContent"}
mergo.Mergo(&dst, src, WithSkipOption(skipFields))
```

**Comment by vtolstov** [comment]
very useful thing, did you mind to provide pr ? =)

**Comment by leopku** [comment]
> very useful thing, did you mind to provide pr ? =)

I had reviewed codes related this feature.
But I found it should be a big change for supporting this feature.
Because I'm new to this project, and had not dive into source codes.
Sorry @vtolstov .

**Comment by imdario** [comment]
Mergo's main branch is frozen for new features. I take note of this feature for the next codebase from scratch.

**Comment by funte** [comment]
@leopku This issue has closed long time, but i still want give you my  advise. You can write the field `AdminContent` a empty string before merge and mego will skip it, its a  small trick.
