### ISSUE TITLE
Proposal: name override struct tag for map merging into struct

### ISSUE THREAD

**Issue by System-Glitch** [imdario/mergo#183]
## Context

When merging maps into structs, using `mergo.Map()`, it is not possible to merge all possible keys.

For example:
```go
type Position struct{
    PosX float64
    PosY float64
}

m := map[string]float64{
    "pos_x": 1,
    "pos_y": 2,
}
```

In this scenario, merging will not work because mergo will use `Pos_X` and `Pos_Y` as keys, which don't exist (and shouldn't exist because of Go naming conventions) in our struct.

## Proposal

For this kind of specific use-case, it would be handy to be able to use struct tags to indicate which field is corresponding to which map key.

```go
type Position struct{
    PosX float64 `mergo:"pos_x"`
    PosY float64 `mergo:"pos_y"`
}
```

Struct tags would have priority over the standard behavior.

## Possible drawback

May have a slight impact on performance.

**Comment by imdario** [comment]
@System-Glitch New features won't be implemented in the current master branch. I'll take this into account for the next version.
