### ISSUE TITLE
Reference to zero should be treated as non-empty value

### ISSUE THREAD

**Issue by UnknownCypher** [imdario/mergo#200]
```
func intP(i int) *int {
	return &i
}

type A struct {
	I *int
}

func TestDefaultConfig(t *testing.T) {
	s := A{I: intP(0)}
	_ = mergo.Merge(&s, &A{I: intP(1)})
	if *s.I != 0 {
		t.Fail()
	}
}
```

I would expect mergo to treat non-nil references as non-empty values, though it does when it references a zero value.

**Comment by imdario** [comment]
@UnknownCypher Zero values are the core behind the merging algorithm. If a pointer contains a zero value, it's virtually the same.

**Comment by jordanlin-g** [comment]
If you would like a work around, something like this transformer should do the trick:

type PtrTransformer struct{}

func (t PtrTransformer) Transformer(typ reflect.Type) func(dst, src reflect.Value) error {
	var vInt32 int32 = 0
	var vInt64 int64 = 0
	var vFloat32 float32 = 0.0
	var vFloat64 float64 = 0.0
	if typ == reflect.TypeOf(&vInt32) ||
		typ == reflect.TypeOf(&vInt64) ||
		typ == reflect.TypeOf(&vFloat32) ||
		typ == reflect.TypeOf(&vFloat64) {
		return func(dst, src reflect.Value) error {
			if dst.IsNil() {
				dst.Set(src)
			}
			return nil
		}
	}
	return nil
}
