### ISSUE TITLE
Update the yaml dependency to v3?

### ISSUE THREAD

**Issue by fubarhouse** [imdario/mergo#206]
Why hello!

Been using mergo for some time and was recently hit by something (link below). Seems the solution is to not use yaml v2 however I've noticed that mergo does use v2 of the yaml package. Is there any chance you'd consider updating it?

https://github.com/go-yaml/yaml/issues/139

**Comment by imdario** [comment]
@fubarhouse @mudler I've merged #212 to upgrade to v3.

**Comment by mudler** [comment]
Thanks for the heads up!
