### ISSUE TITLE
Docs: “Mergo in the wild” inaccurate

### ISSUE THREAD

**Issue by mislav** [imdario/mergo#229]
“Mergo in the wild” lists `cli/cli` as its first item, but I believe that this has been false advertising since May this year, as GitHub CLI did not ever have mergo as a dependency. We [received one PR](https://github.com/cli/cli/pull/5652) from an external contributor that proposes making use of mergo in our codebase, but the PR hasn't been merged yet.

Ref. 194978757031c1a5c8ff8e059ae75fc2fc2a04f7

**Comment by imdario** [comment]
Oh, that's a shame. Maybe I got the wrong repository, but I was granted of the one-time sponsorships the past year from GitHub.

**Comment by imdario** [comment]
@mislav You were right. I checked the official repos and it only appears in two repositories:

![imatge](https://user-images.githubusercontent.com/163009/222543885-60a53129-cfb0-47b8-abb4-c60dfbd8a6a4.png)

I was sure it was also in `cli/cli` but I don't see it in the time I was sure it was. So, I'm removing it from the section.
