### ISSUE TITLE
Issue with type based on time.Time

### ISSUE THREAD

**Issue by iampeter** [imdario/mergo#23]
I have a `Date` type: 
```
type Date time.Time
```
The type is used for date-only JSON representation. I AM using a pointer to Date:

```
type Document struct {
   Created    *Date
}
```

 and `MergeWithOverwrite` does not work unfortunately.

Could you help with this?

**Comment by imdario** [comment]
Yes, sure. I'll check it this weekend.

**Comment by iampeter** [comment]
Thanks @imdario

**Comment by iampeter** [comment]
@imdario any luck with this? thanks

**Comment by imdario** [comment]
No, sorry, I was kinda sick and I didn't have the energy to look at this. I will try this week.

**Comment by iampeter** [comment]
ok thanks @imdario

**Comment by iampeter** [comment]
I just tested with just `*time.Time` (no new type) and it seems to 'go deeper' anyway - does not overwrite.

**Comment by iampeter** [comment]
@imdario, doesn't this:
```
	case reflect.Ptr:
		fallthrough
	case reflect.Interface:
		if src.IsNil() {
			break
		} else if dst.IsNil() {
			if dst.CanSet() && (overwrite || isEmptyValue(dst)) {
				dst.Set(src)
			}
		} else if err = deepMerge(dst.Elem(), src.Elem(), visited, depth+1, overwrite); err != nil {
			return
		}
```

mean that if the destination pointer exists, it will try to deep-merge anyway, instead of overwriting the whole struct the pointer points to?

**Comment by imdario** [comment]
> if the destination pointer exists, it will try to deep-merge anyway, instead of overwriting the whole struct the pointer points to?

Yes, you are right. "overwrite" should be used with dst.IsNil(). If dst is not nil, as in your case, it won't check if it must overwrite it anyway. Good catch! I modify it, test and push it to master.

**Comment by imdario** [comment]
A little test and... Ta-da! That little sneaky bug has been fixed. Please, update your local repository and check if it works for you too.

Sorry for not being able to work on this before.

**Comment by iampeter** [comment]
Great, thanks @imdario !
