### ISSUE TITLE
Why is "You can only merge same-type structs"?

### ISSUE THREAD

**Issue by xh3b4sd** [imdario/mergo#34]
In our microservices we have a strict separation of transport and business logic. That means we implement an endpoint and a service. Both very often have very common request/response structures. So instead of writing all the struct mapping down and having very verbose code I would like to merge these structs dynamically. In the readme it says this.

> You can only merge same-type structs ...

I am wondering for what reason this is. Based on my quick testing [removing these lines works as expected](https://github.com/imdario/mergo/blob/50d4dbd4eb0e84778abe37cefef140271d96fade/merge.go#L119-L121) with the following example. 

```go
package main

import (
	"fmt"

	"github.com/imdario/mergo"
)

type Thir struct {
	Val string
}

type Sec struct {
	F string
	X Thir
}

type Foo struct {
	A string
	B int64
	C Sec
	D string
	F string
}

type Bar struct {
	A string
	B int64
	C Sec
	E int
	F int
}

func main() {
	src := Foo{
		A: "one",
		C: Sec{
			F: "C.F",
			X: Thir{
				Val: "Foo.C.X.Val",
			},
		},
		D: "I am D",
		F: "I am F",
	}

	dest := Bar{
		A: "two",
		C: Sec{
			F: "Bar.C.F",
		},
		B: 2,
		E: 2,
		F: 2,
	}

	err := mergo.Merge(&dest, src)
	if err != nil {
		panic(err)
	}

	fmt.Println(dest)
	// Will print
	// {two 2 {Bar.C.F {Foo.C.X.Val}} 2 2}
}
```

**Comment by imdario** [comment]
First of all, sorry. Second, I will take care of this this next week.

**Comment by xh3b4sd** [comment]
No worries. I thought it was a low hanging fruit and tried to solve it on my own but devil is in the details. It did not work out that easily with all arbitrary objects. E.g. having slices and pointers in structs was an issue IIRC.

**Comment by imdario** [comment]
Merging is a tricky beast. Anyway, I'll try to solve other issues and PRs and visite this one later. If you don't mind, I close it just to make sure I don't leave anything without checking.

**Comment by imdario** [comment]
It had been a long time (2013-2014) but I think this was a design decision to keep Mergo as simple as possible. If I'm not wrong, it should be possible to merge different struct types as long as they share fields with equal name and type.

In the next month I'll work on this. It shouldn't be difficult but it can break things.

**Comment by tigp** [comment]
@imdario Is it still impossible to merge two different types?
