### ISSUE TITLE
Slice and Maps are handled differently

### ISSUE THREAD

**Issue by FrenchBen** [imdario/mergo#35]
Say you have something similar to the example you provided in the README , but instead deal with maps and slices, giving you something like this:
```
package main

import (
	"fmt"
	"github.com/imdario/mergo"
)

type Foo struct {
	A map[string]string
	B []string
}

func main() {
	src := Foo{
		A: make(map[string]string),
		B: []string{"something"},
	}
	src.A["first"] = "1"

	dest := Foo{
		A: make(map[string]string),
		B: []string{"else"},
	}
	dest.A["second"] = "2"
	fmt.Println(src)
	// Will print
	// {map[first:1] [something]}
	fmt.Println(dest)
	// Will print
	// {map[second:2] [else]}

	mergo.Merge(&dest, src)

	fmt.Println(dest)
	// Will print
	// {map[second:2 first:1] [else]}
	// Expected print
	// {map[second:2 first:1] [something else]}
}

```

Why is it that the behavior of Merge is to append to maps but completely over-write the slice?

**Comment by imdario** [comment]
First of all, sorry. Second, I will take care of this this next week.

**Comment by wanghq** [comment]
@imdario any conclusion on this?

**Comment by imdario** [comment]
I'm working out issues and PRs right now (finally, I know). I'll update this as soon as possible.

**Comment by the4thamigo-uk** [comment]
This also is important behaviour for us so we have to roll our own merge function at the moment. Id love to use mergo though as it is more complete.

**Comment by imdario** [comment]
Thanks for the feedback. I'll check this out soon.

**Comment by imdario** [comment]
I must check again map handling in order to be sure that this is the way to go. PR #45 looks good to me but I don't feel sure about this change yet.
