### ISSUE TITLE
Make a release/tag

### ISSUE THREAD

**Issue by rtuin** [imdario/mergo#41]
Hi there,

It's been a while since the latest release (Feb 2016) and updates have been done since.
To make dependency management easier for applications it would be great if mergo can make a new tag/release for changes.

What do you think?

**Comment by imdario** [comment]
Sorry for being so late. I'm going to fix several issues so I made a new release (0.2.3) before changing anything: https://github.com/imdario/mergo/releases/tag/0.2.3
