### ISSUE TITLE
How to reset field to zero value?

### ISSUE THREAD

**Issue by wanghq** [imdario/mergo#43]
Seems there is no way to reset a field to zero value, e.g. reset true with false, reset 1 with 0. Probably the lib shouldn't [follow](https://github.com/imdario/mergo/blob/master/merge.go#L111) a pointer if it points to primitive types.
 
```
type ValueResetExample struct {
	A *bool
	B bool
	C *int
	D int
}

func valueReset() {
	bt := true
	bf := false
	i1 := 1
	i0 := 0
	dst := ValueResetExample{
		A: &bt,
		B: bt,
		C: &i1,
		D: i1,
	}
	src := ValueResetExample{
		A: &bf,
		B: bf,
		C: &i0,
		D: i0,
	}

	err := mergo.MergeWithOverwrite(&dst, src)
	if err != nil {
		panic(err)
	}
	// expected result: A: false, B: false, C: 0, D: 0
	fmt.Printf("A: %v, B: %v, C: %v, D: %v\n", *dst.A, dst.B, *dst.C, dst.D)

	err = mergo.MergeWithOverwrite(&src, dst)
	if err != nil {
		panic(err)
	}
	fmt.Printf("A: %v, B: %v, C: %v, D: %v\n", *src.A, src.B, *src.C, src.D)
}
```

Output
```
A: true, B: true, C: 1, D: 1
A: true, B: true, C: 1, D: 1
```

**Comment by imdario** [comment]
I'll get around this ASAP but I think it's kind of no retro compatible change in behavior.

**Comment by imdario** [comment]
I took longer than expected but I looked it at last. As there is no way to know when a field has a zero-value by default or on purpose, we cannot change it in the core.

You could use a Transformer, introduced in late 2017, to work around this.
