### ISSUE TITLE
Fail on conflict

### ISSUE THREAD

**Issue by the4thamigo-uk** [imdario/mergo#46]
I can see that mergo merges when the destination is non-zero and that there is also a forced overwrite option, but I have a use case where I want to report an error (and abort the merge), if an attempt is made to merge a field that already is non-zero in the destination object. I'd like to submit a PR to support this behaviour. Do you agree that this is useful?

**Comment by imdario** [comment]
It's an interesting idea. Something like TryMerge or MustMerge could be a good name for this behavior.

**Comment by imdario** [comment]
As #49 has been merged, we can implement this easily. I was thinking how to call it and I would go for CleanMerge (as in clean shot). It only would fail if Merge finds a non-zero attribute in destination and the soure attribute isn't zero.

**Comment by imdario** [comment]
@the4thamigo-uk, what do you think about my previous comment? I would love to have feedback about how to call it.
