### ISSUE TITLE
How about subtract?

### ISSUE THREAD

**Issue by blackrosezy** [imdario/mergo#5]
It is nice if we can do the opposite action, subtract/remove.

**Comment by imdario** [comment]
Revisiting this issue. I think we should remove equal fields. I don't see the point to remove different ones (and getting two identical structs).

Yes, I will implement it as this, removing equal fields.

**Comment by PraveenUpadhyay** [comment]
@imdario If you want, I can contribute to this request. Even I am looking for this feature.

**Comment by imdario** [comment]
Go for it, @PraveenUpadhyay. Thanks!
