### ISSUE TITLE
Panics while merging objects which are having nil maps

### ISSUE THREAD

**Issue by sayanh** [imdario/mergo#61]
Trying to merge objects which are having nil maps, I get an exception as `assignment to entry in nil map`
Recommended: If a primitive data type is uninitialized, why don't we initialize that data type and merge?

**Comment by imdario** [comment]
Can you provide a code example, please? Just to be sure about what you try to accomplish.

**Comment by nbrownus** [comment]
I think I am facing a similar problem, here is the shortest example I've come up with so far:

```
	type T struct {
		i map[string][]string
	}


	t1 := T{}
	t2 := T{i:map[string][]string{"hi":{"there"}}}
	mergo.Merge(&t1, t2)
```

Results in
```
panic: assignment to entry in nil map [recovered]
	panic: assignment to entry in nil map
```

**Comment by imdario** [comment]
Issue solved.
