### ISSUE TITLE
Panic when trying to merge a struct with private slice field

### ISSUE THREAD

**Issue by hosszukalman** [imdario/mergo#66]
When you try to merge objects and the destination object has unexoprted slice field, mergo throws a panic: `panic: reflect: reflect.Copy using value obtained using unexported field`

**Comment by Rican7** [comment]
I just ran into this myself 😞

**Comment by jvalentini** [comment]
:+1: Same here

**Comment by imdario** [comment]
Issue solved on release v0.3.3.
