### ISSUE TITLE
Semantic versioning?

### ISSUE THREAD

**Issue by kron4eg** [imdario/mergo#68]
Hello,

I see you doing versioning, and that's awesome! But it's not semantic. Please consider adding `v` as a prefix.

For tools (like dep or vgo) to automatically pick-up release tags those need to be prefixed with `v`, like your latest release 0.3.2, should be `v0.3.2`. dep and vgo will pick those up automatically in that case.

Thanks!

**Comment by imdario** [comment]
You are right. I just edited the last release and I'll keep this format. Thanks!
