### ISSUE TITLE
Merging a struct with itself duplicate elements in slices

### ISSUE THREAD

**Issue by rajatjindal** [imdario/mergo#72]
merging a struct with itself results in duplicate elements in the slice. refer to the attached test which demonstrate the behavior.

https://gist.github.com/rajatjindal/35da5b59f7ba77d963f6191e7d910420

this is causing an issue for me when using client-go of kubernetes, and I am wondering if you can atleast confirm if this is a bug or expected behavior so that i can talk to kubernetes dev about potential workarounds.

Thanks
Rajat Jindal

**Comment by imdario** [comment]
I'm checking this. It looks related to #64 and #35. I think I introduced through PR #45.

**Comment by imdario** [comment]
Confirmed. It was introduced in PR #45 on purpose. The reason was to handle maps and slices in coherent ways. Merge will append to slices as it adds missing keys in maps. It doesn't check for duplicates as appending to a slice doesn't check it either.

The workaround is to write a Transformer.

**Comment by guilhem** [comment]
@imdario maybe it would be awesome to have an option "append if different".

I have some problem here: https://github.com/barpilot/node-labeler-operator/blob/master/service/labeler/controller.go#L120
I'm merging a definition to an actual object when done both must be equal and not append again :)
