### ISSUE TITLE
Merge With Override And AppendSlice fails for map

### ISSUE THREAD

**Issue by prabhu43** [imdario/mergo#94]
Hi @imdario 

We merged two maps with Override and also AppendSlice , which is taking Override as high precedence than AppendSlice for slices too. 

Expected behaviour: We want Override for non-slice and AppendSlice for slice. The following Test should `PASS`, but it's failing currently

```
func TestMergeWithOverrideAndAppendSlice(t *testing.T) {
	aMap := map[string]interface{}{
		"key1": []int{3},
		"key2": "valueA2",
	}

	bMap := map[string]interface{}{
		"key1": []int{1, 2},
		"key2": "valueB2",
		"key3": "valueB3",
	}

	expectedMap := map[string]interface{}{
		"key1": []int{1, 2, 3},
		"key2": "valueB2",
		"key3": "valueB3",
	}
	err := Merge(&aMap, bMap, WithAppendSlice, WithOverride)

	if err != nil {
		t.Errorf("Test failed with error: %v", err)
	}

	if !reflect.DeepEqual(aMap, expectedMap) {
		t.Errorf("Actual: %#v did not match \nExpected: %#v", aMap, expectedMap)
	}
}
```

We went through the code and found it's because of this part of code 

https://github.com/imdario/mergo/blob/master/merge.go#L139

Could you explain the meaning for this code?

**Comment by imdario** [comment]
Sorry for not answering before. Please test this against the last release (v0.3.7) as it fixes some bugs related to Override.

**Comment by prabhu43** [comment]
@imdario It's working as expected in the new version. Thanks!
